name = "FerriteGridUtil"
uuid = "bab52d2a-b59e-463f-9025-b61488042faa"
authors = ["David Rollin <d.rollin@tu-braunschweig.de>", "Phil Kreutzheide <p.kreutzheide@tu-braunschweig.de>"]
version = "1.0.0-DEV"

[deps]
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
Ferrite = "1.0"
HDF5 = "0.17.2"
Makie = "0.21"
OrderedCollections = "1.6.3"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
